### ISSUE TITLE
use scikit-learn instead of sklearn?

### ISSUE THREAD

**Issue by pybokeh** [Speedml/speedml#10]
Is there a plan to migrate to scikit-learn?  I have scikit-learn installed also in my environment and is confusing things and caused deprecation warning:

d:\Miniconda3\envs\notebook\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

**Comment by manavsehgal** [comment]
@pybokeh Speedml uses the latest scikit-learn API. I will specify this more clearly in the docs. The name `sklearn` is the package name used by scikit-learn. I know it is a bit confusing as normally the API names and packages names are consistent like in case of pandas and numpy.

The DeprecationWarning that you are getting may be because of older release of speedml. Latest release is using sklearn.model_selection as suggested by the message. You might want to update to latest release 0.9.x for this message to go away. In case you still get the message, please paste the Notebook cell code causing the message. Hope this helps.

**Comment by pybokeh** [comment]
@manavsehgal Ok thank you, I see now.  Yes it is confusing.  I have always installed scikit-learn via literally "scikit-learn" (pip install scikit-learn).  I did not know that it can also be installed via "sklearn" (pip install sklearn).  Thanks again and I really like this project!

**Comment by manavsehgal** [comment]
@pybokeh many thanks for the appreciation. Hope you continue to find this project useful. Please star and share :-)
