### ISSUE TITLE
Unable to install SpeedML. xgboost issues.

### ISSUE THREAD

**Issue by manavsehgal** [Speedml/speedml#24]
Received from @motithakur on speedml website contact form.

> Unable to install SpeedML. Used pip install, however - xgboost not installing.

**Comment by manavsehgal** [comment]
From @allenlincg on speedml website contact form.

> I get the install fail when in run "pip install Speedml" on my virtual environment of python 2.7.13 for Win 10. The error message is "No files/directories in c:\users\allen\appdata\local\temp\pip-build-qg31oh\xgboost\pip-egg-info (from PKG-INFO)"

**Comment by motisingh65** [comment]
I have been able to resolve this issue at my end

**Comment by manavsehgal** [comment]
@motisingh65 good to know you were able to resolve this at your end. Can you please share with us what worked?

**Comment by motisingh65** [comment]
Here's a summary of how I resolved the problem:

Step 1: Install Homebrew (copy paste the below syntax in the terminal)
/usr/bin/ruby -e "$(curl –fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Step 2: Install gcc (copy paste the below syntax in the terminal)
brew install gcc --without-multilib
It takes a while (about 45 mins) to complete gcc installation

Step 3: Install xgboost (copy paste the below syntax in the terminal)
a) Go to where you want in your filesystem, say <directoy>
b) cd <directory> git clone --recursive https://github.com/dmlc/xgboost
This downloads the XGBoost code into a new directory named xgboost.

Step 4: Now we need to build XGBoost - go to where we downloaded XGBoost
a)
cd <directory>/xgboost
cp make/config.mk ./config.mk (copy paste the below syntax in the terminal)

b) Uncomment the lines near the top of the file - I used vim editor (vi config.mk)
export CC = gcc
export CXX = g++
Save the file

c) Change them to the following:
export CC = gcc-7 (the number here-in will have to match with the gcc version installed – this is critical, else xgboost will not be installed – thus one has to be careful to note the version while gcc is being installed)
export CXX = g++-7 (-do-)
Save the file

Step 5: Also, make changes to the file xgboost/Makefile; change lines 47 and 50 to reflect the commands above. Again, I used vi for this editing.

Step 6: Save file and now run a cleaning step since Makefile has changed
make clean_all && make -j4 (copy paste the below syntax in the terminal)

Step 7: This will ensure clean xgboost installation along with library build

Step 8: Install
cd python-package; python setup.py install (copy paste the below syntax in the terminal)

Step 9: Restart Python/Anaconda to import the library

________________________________

**Comment by manavsehgal** [comment]
@motisingh65 Thanks for this detailed explanation. I will make a note of XGBoost install process in the README.

**Comment by EugedeTomaso** [comment]
A more straightforward solution:
1) $ conda install -c https://conda.anaconda.org/akode xgboost
2) pip install speedml

**Comment by manavsehgal** [comment]
Thanks @EugedeTomaso seems like a better solution to document in the README.

**Comment by manavsehgal** [comment]
Documented @EugedeTomaso solution in README [Install section](https://github.com/Speedml/speedml#install-speedml)

**Comment by motisingh65** [comment]
Thanks Manav..

________________________________

**Comment by romulomadu** [comment]
Hy guys, when I'm trying : 

conda install -c https://conda.anaconda.org/akode xgboost 

the follow error appears when lookingo for fetching package metada:

PackageNotFoundError: Package not found: Conda could not find '

Anyone can help me?
