### ISSUE TITLE
SpeedML codes not Executing

### ISSUE THREAD

**Issue by motisingh65** [Speedml/speedml#25]
I have installed gcc, xgboost, speedml all installed on my machine - however, am still not able to run the speedml codes on my notebooks....is it that I can run SpeedML on projects that are hosted on GitHub only

**Comment by manavsehgal** [comment]
@motisingh65 can you please share your notebook on GitHub so we can have a look. Or, share the code snippet and error message here.

**Comment by motisingh65** [comment]
Manav,

Appreciate your response

I have resolved this one as well. I re-downloaded the speedml-0.9.3 package and it worked on Titanic dataset, though I have yet to test it on other dataset. Will let you know, if I hit a roadblock.

Do you think there should be any issues while using Speedml syntax with any other external data sets?

Regards

Moti

________________________________

**Comment by manavsehgal** [comment]
Hi @motisingh65, The Speedml API has been tested on few competitions from Kaggle. Mostly classification problems with a single target variable. I am opening up the API to easily expose underlying packages like pandas, xgboost, numpy, etc. so that you have same flexibility when using the API as you have when using these packages directly. This should mean wider applicability across datasets. However, you may still find edge cases which API may not handle. Please report these here and I will try and address these in a future release. Thanks for using the API and sharing your experience.
